"""Sequential CL trainer — orchestrates Tasks 1 … T for Scenario B.

Placeholder — implement after all components are ready.
"""

from __future__ import annotations


class CLTrainer:
    """Orchestrates the full Scenario B CL experiment.

    TODO — implement:
      Step 1: DINOv2 (frozen) → extract pooled z and patch tokens for all images
      Step 2: Task 1 only — build PatchCore memory bank from normal images, then freeze
      Step 3: Load concept labels from task CSV (pre-generated by annotation_pipeline)
      Step 4: ConceptDeduplicator — merge synonyms; add genuinely new heads
      Step 5: CONCIL accumulate + solve for concept heads and anomaly head
      Step 6: Recalibrate τ = 95th percentile s_novel on held-out normal images

      Persist after each task: ConcilState (.npz), ConceptHeads weights, τ
    """

    def __init__(self, config: dict):
        raise NotImplementedError("CLTrainer not yet implemented")

    def run_task(self, task_id: int) -> dict:
        """Execute one CL task and return per-task metrics."""
        raise NotImplementedError

    def run_all(self) -> list[dict]:
        """Run all tasks sequentially."""
        raise NotImplementedError
